#!/usr/bin/env node
/**
 * Cookie Sync for OpenClaw
 * 
 * Adapted from browserbase/skills cookie-sync pattern.
 * Extracts cookies from local Chrome (via DevTools) and saves them
 * in a format usable by our browser automation.
 * 
 * Usage:
 *   node cookie-sync.mjs extract [--domains example.com,github.com] [--output cookies.json]
 *   node cookie-sync.mjs list [--domains example.com]
 *   node cookie-sync.mjs import --file cookies.json [--browser-profile stealth-x]
 * 
 * Output: cookies.json in Netscape format (compatible with curl, Playwright, etc.)
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ── CLI args ─────────────────────────────────────────────────────────────────

function parseArgs() {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    console.log(`Cookie Sync for OpenClaw

Usage:
  cookie-sync.mjs extract [--domains example.com,github.com] [--output cookies.json]
  cookie-sync.mjs list [--domains example.com]
  cookie-sync.mjs import --file cookies.json [--profile stealth-x]

Commands:
  extract   Extract cookies from local Chrome DevTools
  list      List available cookies (optionally filtered by domain)
  import    Import cookies into a Chrome profile for browser automation
`);
    process.exit(0);
  }

  const result = { command: args[0], domains: [], output: 'cookies.json', profile: 'stealth-x' };

  for (let i = 1; i < args.length; i++) {
    if (args[i] === '--domains' && args[i + 1]) {
      result.domains = args[++i].split(',').map(d => d.trim().toLowerCase()).filter(Boolean);
    } else if (args[i] === '--output' && args[i + 1]) {
      result.output = args[++i];
    } else if (args[i] === '--profile' && args[i + 1]) {
      result.profile = args[++i];
    } else if (args[i] === '--file' && args[i + 1]) {
      result.inputFile = args[++i];
    }
  }

  return result;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function readJson(p, fallback = null) {
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return fallback; }
}

function writeJson(p, obj) {
  fs.writeFileSync(p, JSON.stringify(obj, null, 2), 'utf8');
}

function writeNetscape(p, cookies) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# This file was generated by OpenClaw cookie-sync',
    '# https://github.com/labsclaw/openclaw-skills',
    '',
  ];

  for (const cookie of cookies) {
    const { domain, path, secure, expires, name, value, httpOnly, sameSite } = cookie;
    
    // Netscape format: domain, flag, path, secure, expires, name, value
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secureFlag = secure ? 'TRUE' : 'FALSE';
    const exp = expires || Math.floor(Date.now() / 1000) + 31536000; // 1 year default
    
    lines.push(`${domain}\t${flag}\t${path}\t${secureFlag}\t${exp}\t${name}\t${value}`);
  }

  fs.writeFileSync(p, lines.join('\n'), 'utf8');
}

function filterByDomains(cookies, domains) {
  if (!domains.length) return cookies;
  return cookies.filter(c => 
    domains.some(d => c.domain === d || c.domain.endsWith('.' + d) || c.domain.includes('.' + d))
  );
}

// ── Chrome DevTools cookie extraction ────────────────────────────────────────

async function extractFromChrome(port = 9222) {
  // Connect to Chrome DevTools and extract cookies
  try {
    const resp = await fetch(`http://127.0.0.1:${port}/json/version`);
    const info = await resp.json();
    const wsUrl = info.webSocketDebuggerUrl;

    const WebSocket = (await import('ws')).default;
    const ws = new WebSocket(wsUrl);
    let msgId = 1;

    return new Promise((resolve, reject) => {
      const timeout = setTimeout(() => {
        ws.close();
        reject(new Error('Timeout extracting cookies'));
      }, 10000);

      ws.on('open', () => {
        ws.send(JSON.stringify({ id: msgId++, method: 'Network.getAllCookies' }));
      });

      ws.on('message', (data) => {
        const msg = JSON.parse(data.toString());
        if (msg.id && msg.result?.cookies) {
          clearTimeout(timeout);
          ws.close();
          resolve(msg.result.cookies);
        } else if (msg.id && msg.error) {
          clearTimeout(timeout);
          ws.close();
          reject(new Error(`CDP error: ${msg.error.message}`));
        }
      });

      ws.on('error', (err) => {
        clearTimeout(timeout);
        reject(err);
      });
    });
  } catch (err) {
    console.error('Failed to connect to Chrome DevTools. Is Chrome running with --remote-debugging-port=9222?');
    throw err;
  }
}

// ── Commands ─────────────────────────────────────────────────────────────────

async function cmdExtract(config) {
  console.log('Extracting cookies from Chrome...');
  
  const cookies = await extractFromChrome();
  const filtered = filterByDomains(cookies, config.domains);
  
  // Save both formats
  writeJson(config.output, filtered);
  const netscapePath = config.output.replace(/\.json$/, '.txt');
  writeNetscape(netscapePath, filtered);
  
  console.log(`Extracted ${filtered.length} cookies`);
  console.log(`  JSON: ${config.output}`);
  console.log(`  Netscape: ${netscapePath}`);
  
  // Show summary by domain
  const byDomain = {};
  for (const c of filtered) {
    byDomain[c.domain] = (byDomain[c.domain] || 0) + 1;
  }
  for (const [domain, count] of Object.entries(byDomain)) {
    console.log(`  ${domain}: ${count}`);
  }
}

async function cmdList(config) {
  if (!fs.existsSync(config.output)) {
    console.error(`Cookies file not found: ${config.output}`);
    console.error('Run "extract" first or specify --output with existing file');
    process.exit(1);
  }
  
  const cookies = readJson(config.output, []);
  const filtered = filterByDomains(cookies, config.domains);
  
  console.log(`${filtered.length} cookies:`);
  for (const c of filtered) {
    const exp = c.expires ? new Date(c.expires * 1000).toISOString() : 'session';
    console.log(`  ${c.domain}\t${c.name}\t${exp}`);
  }
}

async function cmdImport(config) {
  if (!config.inputFile || !fs.existsSync(config.inputFile)) {
    console.error('Input file not found:', config.inputFile);
    process.exit(1);
  }

  const cookies = readJson(config.inputFile, []);
  const filtered = filterByDomains(cookies, config.domains);
  
  console.log(`Importing ${filtered.length} cookies for profile: ${config.profile}`);
  
  // For OpenClaw browser tool, cookies are typically handled via the browser session
  // This would need integration with our browser tool's cookie injection
  // For now, output the format needed
  
  const importPath = path.join(__dirname, `../../../.openclaw/media/inbound/cookies-${config.profile}.json`);
  writeJson(importPath, filtered);
  
  console.log(`Cookies written to: ${importPath}`);
  console.log('Use with browser tool via cookie injection or import into Chrome profile manually.');
}

// ── Main ─────────────────────────────────────────────────────────────────────

const config = parseArgs();

switch (config.command) {
  case 'extract':
    await cmdExtract(config);
    break;
  case 'list':
    await cmdList(config);
    break;
  case 'import':
    await cmdImport(config);
    break;
  default:
    console.error(`Unknown command: ${config.command}`);
    process.exit(1);
}